### ISSUE TITLE
Prepare db migration from ercole v1 to v2

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#236]
We need to implement migration of db from old ercole using PostgreSQL to MongoDB, changing hostdata schema.
Maybe Talend is the right tool.

**Comment by mbolis** [comment]
Talend can:
1. extract data from the v1 database
2. map it to v2 schema
3. insert it into MongoDB

If additional checks are needed upon insertion:
1. an API endpoint should be added to v2
2. Talend can call the endpoint as alternative to insertion into Mongo

Talend jobs can be exported and run as Java programs. Configuration contexts can be exported too, in order to parametrize job execution.

**Comment by cirelli94** [comment]
Closed because unnecessary for now.
