### ISSUE TITLE
Interna meeting - Versioning and release process

### ISSUE THREAD

**Issue by elisaroncalli** [ercole-io/ercole#522]

**Comment by cirelli94** [comment]
Trying to follow https://semver.org/ method and spirit, but not strictly, since this is a product and not a library :)

For all the projects:
Given a version number MAJOR.MINOR.PATCH, increment the:
    MAJOR version when you make big changes or rewrites, like from 1.0 to 2.0 has happened
    MINOR version when you add functionality
    PATCH version when you make backwards compatible bug fixes.

Keeping this in mind:
- `ercole` and `ercole-web` MUST be installed with equal MAJOR and MINOR.
- `ercole-agent` MUST be of the same MAJOR of `ercole`, the compatibility is guaranteed and supported.
